
import { Mission } from './types';

export const ONGOING_MISSIONS: Mission[] = [
  {
    id: '1',
    title: 'React Fundamentals',
    short_description: 'Master the core concepts of React',
    description: 'Master the core concepts of React, including components, state, and props.',
    level: 'Beginner',
    topics_to_cover: ['Components', 'State Management', 'Props', 'Hooks'],
    learning_goal: 'Build interactive React applications',
    byte_size_checkpoints: [
      'Introduction to React',
      'Components and JSX',
      'State and Props',
      'Hooks and Lifecycle',
      'Building a Complete App'
    ],
    skills: ['React', 'JavaScript', 'Frontend'],
    creator_id: 'system',
    is_public: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    progress: 75,
    tags: ['Frontend', 'JavaScript'],
  },
  {
    id: '2',
    title: 'Advanced CSS with Tailwind',
    short_description: 'Learn advanced styling techniques',
    description: 'Learn advanced styling techniques and build complex, responsive layouts with Tailwind CSS.',
    level: 'Intermediate',
    topics_to_cover: ['Tailwind CSS', 'Responsive Design', 'Custom Components'],
    learning_goal: 'Create beautiful, responsive UIs',
    byte_size_checkpoints: [
      'Tailwind CSS Basics',
      'Responsive Design',
      'Custom Components',
      'Advanced Styling',
      'Project Implementation'
    ],
    skills: ['CSS', 'Tailwind', 'UI/UX'],
    creator_id: 'system',
    is_public: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    progress: 40,
    tags: ['CSS', 'UI/UX'],
  },
];

export const AVAILABLE_MISSIONS: Mission[] = [
  {
    id: '3',
    title: 'TypeScript for Professionals',
    short_description: 'Deep dive into TypeScript',
    description: 'Deep dive into TypeScript to write scalable and maintainable applications.',
    level: 'Intermediate',
    topics_to_cover: ['TypeScript Basics', 'Advanced Types', 'Generics', 'Decorators'],
    learning_goal: 'Write scalable TypeScript applications',
    byte_size_checkpoints: [
      'TypeScript Fundamentals',
      'Advanced Type System',
      'Generics and Utility Types',
      'Decorators and Metadata',
      'Real-world Project'
    ],
    skills: ['TypeScript', 'JavaScript', 'Frontend'],
    creator_id: 'system',
    is_public: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    tags: ['Frontend', 'JavaScript'],
  },
  {
    id: '4',
    title: 'State Management with Redux',
    short_description: 'Global state management',
    description: 'Understand and implement global state management in large-scale applications.',
    level: 'Intermediate',
    topics_to_cover: ['Redux Basics', 'Actions', 'Reducers', 'Middleware'],
    learning_goal: 'Implement complex state management',
    byte_size_checkpoints: [
      'Redux Fundamentals',
      'Actions and Reducers',
      'Middleware and Async',
      'Redux Toolkit',
      'Real Application'
    ],
    skills: ['Redux', 'React', 'State Management'],
    creator_id: 'system',
    is_public: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    tags: ['React', 'State Management'],
  },
  {
    id: '5',
    title: 'UI/UX Design Principles',
    short_description: 'Design fundamentals',
    description: 'Learn the fundamental principles of user interface and user experience design.',
    level: 'Beginner',
    topics_to_cover: ['Design Principles', 'User Research', 'Prototyping', 'Usability'],
    learning_goal: 'Create user-centered designs',
    byte_size_checkpoints: [
      'Design Thinking',
      'User Research Methods',
      'Wireframing and Prototyping',
      'Visual Design Principles',
      'Usability Testing'
    ],
    skills: ['UI/UX', 'Design', 'Prototyping'],
    creator_id: 'system',
    is_public: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    tags: ['Design', 'UI/UX'],
  },
  {
    id: '6',
    title: 'Backend with Node.js & Express',
    short_description: 'Build backend services',
    description: 'Build robust and efficient backend services and APIs with Node.js.',
    level: 'Intermediate',
    topics_to_cover: ['Node.js', 'Express.js', 'APIs', 'Database Integration'],
    learning_goal: 'Build scalable backend services',
    byte_size_checkpoints: [
      'Node.js Fundamentals',
      'Express.js Framework',
      'RESTful API Design',
      'Database Integration',
      'Deployment and Scaling'
    ],
    skills: ['Node.js', 'Express', 'Backend', 'APIs'],
    creator_id: 'system',
    is_public: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    tags: ['Backend', 'JavaScript'],
  },
];
